baseURL = "https://navcore.org"
theme = "nav-community-v1"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = false

[Languages]
[Languages.en]
title = "NavCoin Community Site"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"


twitter_username = "navcoin"


#linkedin = "english-link"
#
#languageCode = "en"
#DefaultContentLanguage = "en"
#copyright = "Everything is mine"
#
#
#[languages]
#[languages.en]
#title = "NavCoin Community Site"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true


# Main Menu
[[menu.main]]
    name = "Home"
    title = "Home"
    weight = -100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Information"
    title = "Information"
    weight = -90
    identifier = "information"
    depth = 1
[[menu.main]]
    name = "About NavCoin"
    title = "About NavCoin"
    weight = 1
    url = "/about-navcoin/"
    identifier = "about-NavCoin"
    parent = "information"
[[menu.main]]
    name = "FAQ"
    title = "FAQ"
    weight = 2
    url = "https://info.navcoin.org/faq"
    identifier = "faq"
    parent = "information"
[[menu.main]]
    name = "Technical Support"
    title = "Technical Support"
    weight = 4
    url = "https://info.navcoin.org/"
    identifier = "technical-support"
    parent = "information"
[[menu.main]]
    name = "About This Website"
    title = "About This Website"
    weight = 5
    url = "/about-this-website/"
    identifier = "about-this-website"
    parent = "information"
[[menu.main]]
    name = "Get NAV"
    title = "Get NAV"
    weight = -80
    identifier = "get-nav"
    url = "/projects/order-by-progress/"
[[menu.main]]
    name = "Wallets"
    title = "Wallets"
    weight = -40
    identifier = "wallets"
    url = "/projects/order-by-progress/"
