baseURL = "https://navcore.org"
theme = "nav-community-v1"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = false

[Languages]
[Languages.en]
title = "NavCoin Community Site"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"


twitter_username = "navcoin"


#linkedin = "english-link"
#
#languageCode = "en"
#DefaultContentLanguage = "en"
#copyright = "Everything is mine"
#
#
#[languages]
#[languages.en]
#title = "NavCoin Community Site"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true


# Main Menu
[[menu.main]]
    name = "Home"
    title = "Home"
    weight = 1
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Information"
    title = "Information"
    weight = 2
    identifier = "information"
    depth = 1
[[menu.main]]
    name = "About NavCoin"
    title = "About NavCoin"
    weight = 1
    url = "/about-navcoin/"
    identifier = "about-NavCoin"
    parent = "information"
[[menu.main]]
    name = "Getting Started"
    title = "Getting Started"
    weight = 2
    url = "/getting-started/"
    identifier = "getting-started"
    parent = "information"
[[menu.main]]
    name = "Buying NavCoin"
    title = "Buying NavCoin"
    weight = 3
    url = "/buying-navcoin"
    identifier = "buying-navcoin"
    parent = "information"
[[menu.main]]
    name = "Knowledge Base"
    title = "Knowledge Base"
    weight = 4
    url = "https://info.navcoin.org/"
    identifier = "knowledge-base"
    parent = "information"
[[menu.main]]
    name = "About This Website"
    title = "About This Website"
    weight = 5
    url = "/about-this-website/"
    identifier = "about-this-website"
    parent = "information"
[[menu.main]]
    name = "Contribute"
    title = "Contribute"
    weight = 6
    url = "/contribute/"
    identifier = "contribute"
    parent = "information"
[[menu.main]]
    name = "Wallets"
    title = "Wallets"
    weight = 3
    identifier = "wallets"
    url = "/wallets/"
[[menu.main]]
    name = "Community"
    title = "Community"
    weight = 4
    identifier = "community"
    url = "/community/"
