baseURL = "https://navcoin.org"
theme = "nav-community-v1"

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir = false

[Languages]
[Languages.en]
title = "NavCoin.org"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"


twitter_username = "navcoin"


#linkedin = "english-link"
#
#languageCode = "en"
#DefaultContentLanguage = "en"
#copyright = "Everything is mine"
#
#
#[languages]
#[languages.en]
#title = "NavCoin.org"


[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true


# Main Menu
[[menu.main]]
    name = "About"
    title = "About"
    weight = 1
    url = "/about-navcoin/"
    identifier = "about-NavCoin"

[[menu.main]]
    name = "Learn"
    title = "Learn"
    weight = 2
    identifier = "learn"
    depth = 1
    [[menu.main]]
        name = "Getting Started"
        title = "Getting Started"
        weight = 2
        url = "/getting-started/"
        identifier = "getting-started"
        parent = "learn"
    [[menu.main]]
        name = "Buying NavCoin"
        title = "Buying NavCoin"
        weight = 3
        url = "/buying-navcoin"
        identifier = "buying-navcoin"
        parent = "learn"
    [[menu.main]]
        name = "Knowledge Base"
        title = "Knowledge Base"
        weight = 4
        url = "https://info.navcoin.org/"
        identifier = "knowledge-base"
        parent = "learn"
    [[menu.main]]
        name = "About This Website"
        title = "About This Website"
        weight = 5
        url = "/about-this-website/"
        identifier = "about-this-website"
        parent = "learn"
    [[menu.main]]
        name = "Contribute"
        title = "Contribute"
        weight = 6
        url = "/contribute/"
        identifier = "contribute"
        parent = "learn"

[[menu.main]]
    name = "Community"
    title = "Community"
    weight = 3
    identifier = "community"
    [[menu.main]]
        name = "Community Hub"
        title = "Community Hub"
        weight = 1
        identifier = "community-hub"
        url = "https://www.navhub.org"
        parent="community"
    [[menu.main]]
        name = "NavTech Servers"
        title = "NavTech Servers"
        weight = 2
        identifier = "navtech-servers"
        url = "https://navtechservers.com/"
        parent="community"
    [[menu.main]]
        name = "NavCommunity"
        title = "NavCommunity"
        weight = 3
        identifier = "navcommunity"
        url = "https://navcommunity.net/"
        parent="community"
    [[menu.main]]
        name = "NavCoin Italia"
        title = "NavCoin Italia"
        weight = 4
        identifier = "navcoin-italia"
        url = "https://www.navcoinitalia.com/"
        parent="community"


[[menu.main]]
    name = "Downloads"
    title = "Downloads"
    weight = 4
    identifier = "downloads"
    [[menu.main]]
        name = "NavCoin Core"
        title = "NavCoin Core"
        weight = 1
        identifier = "navcoin-core"
        url = "/downloads/navcoin-core"
        parent="downloads"
    [[menu.main]]
        name = "NavPay"
        title = "NavPay"
        weight = 2
        identifier = "navpay"
        url = "/downloads/navpay"
        parent="downloads"
    [[menu.main]]
        name = "All Downloads"
        title = "All Downloads"
        weight = 3
        identifier = "all-downloads"
        url = "/downloads/"
        parent="downloads"